version: 2

base-image:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "30 * * * *"
    allow:
      update-types: "version-update:semver-minor"
