version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 1
      include:
        - "fedora/fedora-bootc"
    ignore:
      - dependency-name: "fedora/fedora-bootc"
        versions: [">= 45"]
