version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0,30 * * * *"
    allow:
      update-types: "version-update:semver-minor"
