name: merge dependabot pr and build image

on: pull_request_target

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'lfchr/linux-scheduled-updates'
    steps:
      - name: dependabot
        uses: dependabot/fetch-metadata@v3
      - name: merge
        run: gh pr merge -m "${{github.event.pull_request.html_url}}"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  build:
    uses: lfchr/linux/.github/workflows/build-push-ghcr.yml@main
    if: ${{ jobs.merge.if == 'success' }}
    with:
      image-tag: latest
      ghcr-user: ${{ github.actor }}
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
